### ISSUE TITLE
How to set a List<String> in json file

### ISSUE THREAD

**Issue by javyliu** [fadhilx/json_to_model#10]
If i set 'strArray': '$[]String' in json file, it will add a 'import String.dart' in generated model, how to fix it?

**Comment by fadhilx** [comment]
in this case you just need to use normal array since normal array is valid in JSON

```json
{
    "strArray": [""]
}
```

Edit: so far it will return as `List<dynamic>`. may be i will improve the type conversion

**Comment by Mooibroek** [comment]
I can take a look at improving the type conversion in the nearby future, seems like a good idea to support atleast the most basic primitives like `string`, `int`, `double` and `boolean`.

**Comment by fadhilx** [comment]
Thank you @Mooibroek

**Comment by mark-nicepants** [comment]
@javyliu This should now properly work if a new version is put on pub.dev 

```json
{
    "strArray": [""]
}
```

Will resolve in a `List<String`.

You can now also have complex nested json in an List

```json
{
  "data": {
    "id": "string",
    "title": "string",
    "items": [
      {
        "$key": "CategoryItem",
        "entity": "@enum:form,document",
        "form_response": "$form_response",
        "document": "$document"
      }
    ]
  },
  "meta" : {
    "forms" : "$[]form_template"
  }
}
```

Because we dont have keys you can add a "$key" value to the list object. That will be used for the inner class name.

**Comment by zigang93** [comment]
May I know when it will be released?
