### ISSUE TITLE
Hey,my problem: json file's int enum convert

### ISSUE THREAD

**Issue by jiyunkeji** [fadhilx/json_to_model#15]
json_to_model: 1.4.0

see the picture:

<img width="472" alt="image" src="https://user-images.githubusercontent.com/50569560/91959747-9eb90380-ed3b-11ea-8001-3e153f333808.png">

why after output file is String:

<img width="566" alt="image" src="https://user-images.githubusercontent.com/50569560/91959996-ed669d80-ed3b-11ea-9317-b26368630941.png">

**Comment by mark-nicepants** [comment]
Tested this with version 2.3.0 and seems to be working fine with that syntax. Closing, please comment if the issue still persists
