### ISSUE TITLE
Flutter 2 support

### ISSUE THREAD

**Issue by zigang93** [fadhilx/json_to_model#16]
migrate/enable nullable feature into this package.
How do I update this package to compatible with latest json_serializable?

**Comment by mark-nicepants** [comment]
A while ago I forked this repo because its no longer actively maintained. 
You can try this one what has null safety behind a -nullsafety flag

https://pub.dev/packages/apn_json2model

**Comment by zigang93** [comment]
~~still have problem with your 2.1.0-nullsafety version
'required' key is wrong.. should be '@required' after generate the file..
nvm I go build my own packages..~~

sorry, I just realised the "@required" already change to 'required'
