### ISSUE TITLE
Flutter 2 failed with no *.g.dart

### ISSUE THREAD

**Issue by Attiv** [fadhilx/json_to_model#17]
**Describe the bug**
Flutter 2 failed with no *.g.dart

**To Reproduce**
1. user Flutter2
2. run `flutter pub run json_to_model`

**Expected behavior**
no error

**Screenshots**
![](https://i.loli.net/2021/04/14/RAXwdcoM9eBFtVZ.png)

**Comment by mark-nicepants** [comment]
I updated the repo with a new version, please be aware that is is a breaking update (json_serializable dependency is dropped)
