### ISSUE TITLE
Generate class with the capable to inherit from another classes

### ISSUE THREAD

**Issue by longph123** [fadhilx/json_to_model#18]
Can you please add feature to be generating a class with the possibility of inheritance from another classes?

I have a Json class like this and i want it's generated class can be inherited from another class (like UserSalesRegion extends BaseSalesRegion ...), so pls add more expression to do it. Tks so much!
<img width="485" alt="Screen Shot 2021-05-16 at 17 14 27" src="https://user-images.githubusercontent.com/37921321/118393598-39f3ce00-b66a-11eb-9534-35eb0f0a80b4.png">

**Comment by mark-nicepants** [comment]
The author sadly doesnt update this repo anymore. I made fork of this that is still active. We also have support for `extends` altho its undocumented at the moment. I would love to help you there if you open a ticket there.

https://pub.dev/packages?q=apn_json2model

**Comment by mark-nicepants** [comment]
@longph123 I have obtained maintainer status on this project and have updated this repo with all changes in apn_json2model. Can you upgrade to version 2.3.0 and check if it is working?

The syntax should be something like this:

in person.json
```"@extends": "PageResponse<CategoryItem>",```

the class signature will be
```class Person extends PageResponse<CaregoryItem>{```

You can also specify @override on certain keys

![image](https://user-images.githubusercontent.com/62654433/119183634-a7419d80-ba74-11eb-9e41-22b9d45b81b0.png)

Please let me know with a comment if you need more help.
