### ISSUE TITLE
Underlined file names cannot be converted to camelcase class names

### ISSUE THREAD

**Issue by SpanishOnion** [fadhilx/json_to_model#2]
for example:

file name: `article_sort.json`

Currently generating is：

`
class Articlesort {}
`

want to be:

`
class ArticleSort {}
`

Can you support this feature?

**Comment by fadhilx** [comment]
will take a look, it suppose to be PascalCase/camelCase. it might have something to do with `core/extensions.dart`

**Comment by fadhilx** [comment]
@SpanishOnion Ok its fixed now, please update your pub dependency to `1.3.11`, tell me if you got new error/bug after this update.

**Comment by SpanishOnion** [comment]
Still a bit wrong.
The `.g.dart` file was not generated

for example:

```
part 'articleSort.g.dart'; // this file was not generated, and file name is also wrong, Its name should be 'article_sort.g.dart'

@JsonSerializable()
class ArticleSort {

}
```

**Comment by fadhilx** [comment]
@SpanishOnion Ok, thank you, i fixed it, please update your pub dependency to `1.3.12`, tell me if you got new error/bug after this update.

**Comment by SpanishOnion** [comment]
There are still a few mistakes.

The `article_sort.g.dart` file was generated, but there is a syntax error in the `article_sort.dart` file

For example, the content of `article_sort.dart` file is:

```
part 'articleSort.g.dart';// syntax error

@JsonSerializable()
class ArticleSort {}
```

The correct syntax should be:

```
part 'article_sort.g.dart';
```

**Comment by SpanishOnion** [comment]
Now it works normally, it may be due to a cache problem, I deleted the old file and ran it again and it worked.

Thank you for your work.

**Comment by fadhilx** [comment]
Ok im closing this issue.
