### ISSUE TITLE
Why use a new file for the array

### ISSUE THREAD

**Issue by anstns** [fadhilx/json_to_model#20]

**Comment by Mooibroek** [comment]
Thats not a requirement

This example will work. 
```json
{
   "items": [
        { "name": "Mark" }
    ]
}
```

You do need to specify a key with a classname. The library will look for the first item in the list for a key named $key and use that name for the child class.

```json
{
   "items": [
        { "$key": "User", "name": "Mark" },
        { "name": "Mark" },
    ]
}
```
