### ISSUE TITLE
get a error like this

### ISSUE THREAD

**Issue by chenyi2006520** [fadhilx/json_to_model#21]
Unhandled exception:
Quiver is needed to generate models (To support `null` in copyWith and mocks). Please run `flutter pub add quiver`

#0      PubspecParser.parse (package:json_to_model/config/pubspec_parser.dart:26:7)
<asynchronous suspension>
#1      main (file:///usr/local/share/flutter/.pub-cache/git/json_to_model-216e313033e126a9ebf89fcb559152d84e96b7b9/bin/json_to_model.dart:7:26)
<asynchronous suspension>

flutter version info:
Flutter 2.5.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4cc385b4b8 (25 hours ago) • 2021-09-07 23:01:49 -0700
Engine • revision f0826da7ef
Tools • Dart 2.14.0

**Comment by Mooibroek** [comment]
There is an error in that message. It needs to be `flutter pub add clock`. Ill update it asap

**Comment by Mooibroek** [comment]
Fixed in v3.0.1
