### ISSUE TITLE
Dynamic keys

### ISSUE THREAD

**Issue by redDwarf03** [fadhilx/json_to_model#22]
Great work! thx!
I would like if you can add the parsing of json with dynamic keys like
```
{"TEST18": {"amount": "0.004216338300000002", "amount_int": 4216338300000002}, "TEST2": {"amount": "2.36", "amount_int": 236}}
```
Actually, the generated dart has these properties:

```
  final TEST18 tEST18;
  final TEST2 tEST2;
```
But i would like Map

Thx

**Comment by Mooibroek** [comment]
I think you can use this syntax for this use case :-)

```json
{
  "countries": "#Map<String, dynamic>"
}
```

**Comment by mark-nicepants** [comment]
Correct, with this syntax you can even parse the Map yourself.
