### ISSUE TITLE
With the transition to version 3.0.1, the "double" and "dynamic" type stopped working.

### ISSUE THREAD

**Issue by jeecrypt** [fadhilx/json_to_model#23]
Thanks for the very helpful library!
Thanks especially for the opportunity to use "#Map"
With the transition to version 3.0.1, the "double" type stopped working.
I also need to use a "dynamic" type (previously I was able to achieve this using "null").
Is there a way to use these types in 3.x.x version?

![ScreenShot 2021-10-27 в 21 44 48](https://user-images.githubusercontent.com/47499775/139110378-c0656647-b297-4a1c-8c02-22dc92b2fd6a.png)

**Comment by mark-nicepants** [comment]
Version 3.0.2 (available later today) will bring back double support. Thanks to PR https://github.com/fadhilx/json_to_model/pull/24 provided by @saad4software
