### ISSUE TITLE
yamlScalarToDartObject 

### ISSUE THREAD

**Issue by etoiledemer** [fadhilx/json_to_model#26]
```
type 'Null' is not a subtype of type 'Object' in type cast
#0      yamlScalarToDartObject (package:json_to_model/utils/yaml_utils.dart:37:66)
```

Failure is due to `pubspec.yaml` containing a line like this:
```
json_to_model: 
```
(which is legal to not specify a version)

fixed by changing the line in `pubpsec` to
```
json_to_model: any
```

**Comment by mark-nicepants** [comment]
I believe this is fixed in version 3.0.1  that currently on pub.dev.
