### ISSUE TITLE
looking for clock instead of quiver

### ISSUE THREAD

**Issue by etoiledemer** [fadhilx/json_to_model#27]
error in `pubspec_parser.dart`

it looks for `clock` package, but the error message tells it needs the  `quiver` package

`final quiverInPubspec = (map['dependencies'] as Map<String, dynamic>?)?['clock'] as String?;`

**Comment by mark-nicepants** [comment]
Thanks for letting me know. Will be fixed in 3.0.2 (probably will publish this version to pub.dev today.)
