### ISSUE TITLE
support for epoch timestamp

### ISSUE THREAD

**Issue by ameerfayiz** [fadhilx/json_to_model#35]
**Is your feature request related to a problem? Please describe.**
there is not support for timestamp. 

**Describe the solution you'd like**

- `fromJson `of the time stamp should be `=> DateTime.fromMillisecondsSinceEpoch(int.parse(json['timestamp'].toString())),`
- `toJson `of time stamp should be `=> timestamp.millisecondsSinceEpoch`

**Additional context**
Now i am manually changing dateTime fields in every models to time stamp fields.

**Comment by mark-nicepants** [comment]
Nice idea, ill try to add this in the upcoming 3.1.7 

Will work like this then:
```json
{
    "timeStamp":  "@timestamp"
}
```

**Comment by mark-nicepants** [comment]
Added and published to pub.dev
