### ISSUE TITLE
[Improvement] Nested model parsing

### ISSUE THREAD

**Issue by Mooibroek** [fadhilx/json_to_model#4]
**Is your feature request related to a problem? Please describe.**
I would like to suggest that when the parser sees a Map or a List. I will try to parse them as a separate model. This will allow a much more streamlined copy/pasting from (for example) api docs!

**Describe the solution you'd like**
Given this example: 

- error_response.json

```json
{
  "error": {
    "message": "string",
    "status_code": 0
  }
}
```

With the current parser it will generate something like this:

``` dart
@JsonSerializable()
class ErrorResponse {
      ErrorResponse();

  Map<String, dynamic> error;

  factory ErrorResponse.fromJson(Map<String,dynamic> json) => _$ErrorResponseFromJson(json);
  Map<String, dynamic> toJson() => _$ErrorResponseToJson(this);
}
```

It would be very helpfull that it would detect the nested model and create an extra class in the generated file. Something like this would be generated then:

``` dart

@JsonSerializable()
class ErrorResponse {
      ErrorResponse();

  Error error;

  factory ErrorResponse.fromJson(Map<String,dynamic> json) => _$ErrorResponseFromJson(json);
  Map<String, dynamic> toJson() => _$ErrorResponseToJson(this);
}

@JsonSerializable()
class Error {
      Error();

  String message;
  @JsonKey(name: 'status_code') int statusCode;

  factory Error.fromJson(Map<String,dynamic> json) => _$ErrorFromJson(json);
  Map<String, dynamic> toJson() => _$ErrorToJson(this);
}

```
The class name can be deferred from the key (singular key value when it is a list)

**Comment by fadhilx** [comment]
Cool suggestion, i will consider to add that feature.

**Comment by Mooibroek** [comment]
@fadhilx Did you have a chance to look at the open PR? If I need to do any changes, let me know :-)
